/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSTree_Native */

#ifndef _Included_com_itsaky_androidide_treesitter_TSTree_Native
#define _Included_com_itsaky_androidide_treesitter_TSTree_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSTree_Native
 * Method:    edit
 * Signature: (JLcom/itsaky/androidide/treesitter/TSInputEdit;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_edit
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTree_Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTree_Native
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTree_Native
 * Method:    rootNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_rootNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTree_Native
 * Method:    getLanguage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTree_00024Native_getLanguage
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
