/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TreeSitter */

#ifndef _Included_com_itsaky_androidide_treesitter_TreeSitter
#define _Included_com_itsaky_androidide_treesitter_TreeSitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TreeSitter
 * Method:    getLanguageVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TreeSitter_getLanguageVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TreeSitter
 * Method:    getMinimumCompatibleLanguageVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TreeSitter_getMinimumCompatibleLanguageVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
