/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSParser_Native */

#ifndef _Included_com_itsaky_androidide_treesitter_TSParser_Native
#define _Included_com_itsaky_androidide_treesitter_TSParser_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSParser_Native
 * Method:    newParser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_newParser
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSParser_Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSParser_Native
 * Method:    setLanguage
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_setLanguage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSParser_Native
 * Method:    getLanguage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_getLanguage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSParser_Native
 * Method:    parseBytes
 * Signature: (J[BII)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_parseBytes
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSParser_Native
 * Method:    incrementalParseBytes
 * Signature: (JJ[BII)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSParser_00024Native_incrementalParseBytes
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
