/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSLanguages_Native */

#ifndef _Included_com_itsaky_androidide_treesitter_TSLanguages_Native
#define _Included_com_itsaky_androidide_treesitter_TSLanguages_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    agda
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_agda
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    bash
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_bash
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    c
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_c
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    cSharp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_cSharp
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    cpp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_cpp
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    css
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_css
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    dart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_dart
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    elm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_elm
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    embeddedTemplate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_embeddedTemplate
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    eno
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_eno
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    go
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_go
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    haskell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_haskell
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    html
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_html
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    java
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_java
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    javascript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_javascript
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    julia
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_julia
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    kotlin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_kotlin
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    lua
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_lua
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    markdown
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_markdown
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    ocaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_ocaml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    php
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_php
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    python
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_python
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    ruby
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_ruby
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    rust
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_rust
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    scala
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_scala
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    scss
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_scss
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    swift
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_swift
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    toml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_toml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    tsx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_tsx
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    typescript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_typescript
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    vue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_vue
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    yaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_yaml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages_Native
 * Method:    wasm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_00024Native_wasm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
