/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSLanguages */

#ifndef _Included_com_itsaky_androidide_treesitter_TSLanguages
#define _Included_com_itsaky_androidide_treesitter_TSLanguages
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    agda
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_agda
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    bash
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_bash
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    c
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_c
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    cSharp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_cSharp
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    cpp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_cpp
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    css
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_css
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    dart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_dart
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    elm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_elm
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    embeddedTemplate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_embeddedTemplate
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    eno
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_eno
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    go
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_go
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    haskell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_haskell
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    html
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_html
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    java
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_java
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    javascript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_javascript
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    julia
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_julia
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    kotlin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_kotlin
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    lua
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_lua
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    markdown
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_markdown
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    ocaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_ocaml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    php
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_php
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    python
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_python
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    ruby
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_ruby
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    rust
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_rust
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    scala
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_scala
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    scss
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_scss
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    swift
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_swift
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    toml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_toml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    tsx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_tsx
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    typescript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_typescript
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    vue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_vue
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    yaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_yaml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguages
 * Method:    wasm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSLanguages_wasm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
