/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative */

#ifndef _Included_com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
#define _Included_com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    symCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_symCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    fldCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_fldCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    symForName
 * Signature: (J[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_symForName
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jboolean);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    symName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_symName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    fldNameForId
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_fldNameForId
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    fldIdForName
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_fldIdForName
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    symType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_symType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_TSLanguageNative
 * Method:    langVer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024TSLanguageNative_langVer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
