/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_Languages */

#ifndef _Included_com_itsaky_androidide_treesitter_Languages
#define _Included_com_itsaky_androidide_treesitter_Languages
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    agda
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_agda
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    bash
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_bash
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    c
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_c
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    cSharp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_cSharp
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    cpp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_cpp
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    css
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_css
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    dart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_dart
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    elm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_elm
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    embeddedTemplate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_embeddedTemplate
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    eno
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_eno
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    go
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_go
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    haskell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_haskell
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    html
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_html
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    java
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_java
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    javascript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_javascript
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    julia
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_julia
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    kotlin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_kotlin
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    lua
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_lua
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    markdown
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_markdown
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    ocaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_ocaml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    php
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_php
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    python
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_python
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    ruby
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_ruby
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    rust
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_rust
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    scala
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_scala
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    scss
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_scss
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    swift
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_swift
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    toml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_toml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    tsx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_tsx
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    typescript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_typescript
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    vue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_vue
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    yaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_yaml
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_Languages
 * Method:    wasm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_Languages_wasm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
