/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSQueryCursor_Native */

#ifndef _Included_com_itsaky_androidide_treesitter_TSQueryCursor_Native
#define _Included_com_itsaky_androidide_treesitter_TSQueryCursor_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSQueryCursor_Native
 * Method:    newCursor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_newCursor
  (JNIEnv *, jclass);

/*
 * Class:     com_itsaky_androidide_treesitter_TSQueryCursor_Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSQueryCursor_Native
 * Method:    exec
 * Signature: (JJLcom/itsaky/androidide/treesitter/TSNode;)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSQueryCursor_00024Native_exec
  (JNIEnv *, jclass, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
