/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSTreeCursor_Native */

#ifndef _Included_com_itsaky_androidide_treesitter_TSTreeCursor_Native
#define _Included_com_itsaky_androidide_treesitter_TSTreeCursor_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    newCursor
 * Signature: (Lcom/itsaky/androidide/treesitter/TSNode;)J
 */
JNIEXPORT jlong JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_newCursor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    currentTreeCursorNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSTreeCursorNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentTreeCursorNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    currentFieldName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentFieldName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    currentNode
 * Signature: (J)Lcom/itsaky/androidide/treesitter/TSNode;
 */
JNIEXPORT jobject JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_currentNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    gotoFirstChild
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoFirstChild
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    gotoNextSibling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoNextSibling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSTreeCursor_Native
 * Method:    gotoParent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_itsaky_androidide_treesitter_TSTreeCursor_00024Native_gotoParent
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
