/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itsaky_androidide_treesitter_TSLanguage_Native */

#ifndef _Included_com_itsaky_androidide_treesitter_TSLanguage_Native
#define _Included_com_itsaky_androidide_treesitter_TSLanguage_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    symCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    fldCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_fldCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    symForName
 * Signature: (J[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symForName
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jboolean);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    symName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    fldNameForId
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_fldNameForId
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    fldIdForName
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_fldIdForName
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    symType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_symType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_itsaky_androidide_treesitter_TSLanguage_Native
 * Method:    langVer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_itsaky_androidide_treesitter_TSLanguage_00024Native_langVer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
