package com.itsaky.androidide.treesitter;

/**
 * @author Akash Yadav
 */
public class TreeSitter {

  /**
   * The latest ABI version that is supported by the current version of the library. When Languages
   * are generated by the Tree-sitter CLI, they are assigned an ABI version number that corresponds
   * to the current CLI version. The Tree-sitter library is generally backwards-compatible with
   * languages generated using older CLI versions, but is not forwards-compatible.
   */
  public static native int getLanguageVersion();

  /** The earliest ABI version that is supported by the current version of the library. */
  public static native int getMinimumCompatibleLanguageVersion();
}
